name: API Routes Tests
run-name: ${{ github.actor }} is testing ${{ github.repository }}

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Create .env file
        run: |
          echo "APP_PORT=${{ secrets.APP_PORT }}" > .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test